# Generated by Django 6.0.3 on 2026-03-13 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0002_auto_20260313_1448'),
    ]

    operations = [
    ]
