# Generated by Django 6.0.3 on 2026-03-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0003_auto_20260313_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarea',
            name='cancelada',
            field=models.BooleanField(default=False, verbose_name='Cancelada'),
        ),
    ]
